name: build

on:
  push:
    branches:
      - 'master'
      - 'main'
    tags:
      - 'v*'
      - '*.*.*'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
      -
        name: Install mage
        run: go install github.com/magefile/mage@v1.11.0
      -
        name: Mage build
        run: mage build
      -
        name: UPX compress
        uses: crazy-max/ghaction-upx@v4
        if: success()
        with:
          version: latest
          files: bin/nodejs-portable.exe
          args: -fq
      -
        name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nodejs-portable-windows-386
          path: bin/nodejs-portable.exe

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      -
        name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nodejs-portable-windows-386
          path: bin
      -
        name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: bin/nodejs-portable.exe
          name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
